apiVersion: autoscaling/v2 #v2 para suportar múltiplas métricas
kind: HorizontalPodAutoscaler
metadata:
  name: oficina-mecanica-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: oficina-mecanica-deployment
  minReplicas: 1 # Mesmo valor do Deployment
  maxReplicas: 10
  metrics:
  - type: Resource # Estamos usando métricas de recursos padrão (CPU/Memória).
    resource:
      name: cpu
      target:
        type: Utilization # Queremos mirar em um percentual de utilização.
        # Escala se a média de uso de CPU entre todos os pods passar de 70%.
        averageUtilization: 70
        
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        # Escala se a média de uso de Memória entre todos os pods passar de 70%.
        averageUtilization: 70