apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  # PV e StorageClass já é provisionado pelo AWS EBS no Cluster EKS
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi