# Nome do workflow que aparecerá na aba "Actions" do GitHub
name: Validar Pull Request

# Trigger: acionado em todo pull request para a branch 'main'
on:
  pull_request:
    branches: [ "main" ]

jobs:
  # O nome do nosso job. É este nome que usaremos na regra de proteção.
  build-and-test:
    runs-on: ubuntu-latest

    # Necessário write para publicar o relatório de testes
    permissions:
      checks: write

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar .NET 9.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Encontrar arquivo da Solution (.sln)
        id: find_sln
        run: echo "sln_path=$(find . -name '*.sln' -print -quit)" >> $GITHUB_OUTPUT
        
      - name: Restaurar dependências
        run: dotnet restore ${{ steps.find_sln.outputs.sln_path }}

      - name: Buildar a aplicação (Release)
        run: dotnet build ${{ steps.find_sln.outputs.sln_path }} --no-restore --configuration Release

      - name: Rodar testes unitários (Release)
        run: dotnet test ${{ steps.find_sln.outputs.sln_path }} --no-build --configuration Release --verbosity normal --logger "trx;LogFileName=test-results.trx"
        # Permite que o workflow continue mesmo se os testes falharem, para que o relatório possa ser gerado.
        continue-on-error: true
        env:
          # Valores dummy para o appsettings necessários para os testes
          DatabaseConnection__Host: "localhost"
          DatabaseConnection__Port: "5432"
          DatabaseConnection__DatabaseName: "db_test"
          DatabaseConnection__User: "test_user"
          DatabaseConnection__Password: "test_password"
          Jwt__Key: "dummy-super-secret-key-for-testing-purposes-only"
          ApiCredentials__ClientId: "test-client"
          ApiCredentials__ClientSecret: "test-secret"

      - name: Publicar relatório de testes
        uses: dorny/test-reporter@v1
        # Garante que este passo sempre rode, para que possamos ver o relatório mesmo em caso de falha
        if: always()
        with:
          name: test-report
          path: "**/test-results.trx"
          reporter: dotnet-trx
          # Falha o job se algum teste tiver falhado, garantindo que o PR seja bloqueado
          fail-on-error: true

